---
title: "MeroVent"
author: "ES"
date: "9/19/2021"
output:
  html_document:
    keep_md: true

---

```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, cache.lazy = FALSE, warning = FALSE, message = FALSE)
require(tidyverse)
require(magrittr)
require(ggplot2)
require(metR)

PTA <- 0.9
MIC <- 2

CKDEPI.subset <- c(80, 90)
CKDEPI.c.subset <- c(80, 85, 90)

LOGPRO.subset <- c(2.699, 3)
LOGPRO.c.subset <- c(2.5, 2.7, 3)
dose.c.subset <- c(3,4,5,6)
```

# Load and prepare data

```{r}
dd <- read.table('./../sdtab020_1GB_clean_15', header = TRUE) %>%
  mutate(across(everything(), as.numeric)
         , dose = c(1.5, 3, 6, 9, 12, 18)[ceiling(ID/128)]) %>% 
  filter(TIME==96) %>% 
  group_by(ID, CKDEPI, LOGPRO, dose) %>% 
  summarise(p = sum(C_VENT>=MIC)/n()) %>% 
  ungroup() %>% group_by(CKDEPI, LOGPRO) %>% arrange(CKDEPI, LOGPRO) %>%
  mutate(p = pmax(p, lag(p, n = 1, default = 0)))
```

Six discrete doses represent 1.5, ..., 8g of daily Meropenem. LOGPRO measures protein concentrations in log10 ([mg/l]).
# Replication of figures from manuscript
```{r}
dd %>% 
  ggplot(aes(x = CKDEPI, y = LOGPRO, fill = p)) +
  geom_tile() +
  facet_wrap(~dose) +
  scale_fill_gradient2(low = 'red', mid = 'yellow', high = 'darkgreen', midpoint = .5)

dd %>% 
  filter(CKDEPI %in% CKDEPI.subset & LOGPRO %in% LOGPRO.subset) %>% 
  ggplot(aes(x = dose, y = p)) +
  geom_point() + geom_line() +
  facet_grid(CKDEPI ~ LOGPRO) +
  scale_fill_gradient2(low = 'red', mid = 'yellow', high = 'darkgreen', midpoint = .5)
```

## Inversion

```{r}
dd %>% ungroup() %>%  group_by(CKDEPI, LOGPRO) %>% 
  filter(p>=PTA) %>% slice(which.min(dose)) %>% 
  ggplot(aes(x = CKDEPI, y = 10^LOGPRO, fill = as.factor(dose))) +
  geom_tile() +
  scale_y_continuous(trans = 'log10')
```


# Interpolation

## Only dose

```{r echo=TRUE, message=FALSE, warning=FALSE, results=FALSE}
d.plot1 <- dd %>% 
  ungroup() %>% group_by(CKDEPI, LOGPRO) %>% nest() %>% 
  mutate(
    #tps = map(data, ~fields::Tps(.$dose, .$p, lambda = 0.005))
    #     , tps.r = map(tps, ~.$fitted.values)
    #     , dose.c = map(tps, ~dose.c.range)
    #     , p = map(tps, ~predict(., dose.c.range)[,1])
         , sp = map(data, ~data.frame(spline(.$dose, .$p, method = 'hyman', xout = dose.c.range)) %>% setNames(c('dose.c','p')))
         ) %>%
  unnest(sp)
```

```{r}
d.plot1 %>% 
  filter(CKDEPI %in% CKDEPI.subset & LOGPRO %in% LOGPRO.subset) %>% 
  ggplot(aes(x = dose.c, y = p)) +
  geom_point(data = dd %>% filter(CKDEPI %in% CKDEPI.subset & LOGPRO %in% LOGPRO.subset), aes(x=dose)) +
  geom_line(aes(x=dose.c, y=p), color = 'orange') +
  ggalt::geom_xspline(data = (dd %>% filter(CKDEPI %in% CKDEPI.subset & LOGPRO %in% LOGPRO.subset)), aes(x=dose), spline_shape = -.25, color = 'darkgreen') +
  facet_grid(CKDEPI ~ LOGPRO)

```


```{r}
d.plot1 %>% 
  filter(dose.c %in% c(3,3.5,4)) %>% 
  ggplot(aes(x = CKDEPI, y = 10^LOGPRO, fill = p)) +
  geom_tile() +
  facet_grid(~dose.c) +
  scale_fill_gradient2(low = 'red', mid = 'yellow', high = 'darkgreen', midpoint = .5) +
  scale_y_continuous(trans = 'log10')

```

### Inversion

```{r}
d.plot1 %>% ungroup() %>%  group_by(CKDEPI, LOGPRO) %>% 
  filter(p>=PTA) %>% 
  slice(which.min(dose.c)) %>%
  ungroup() %>% 
  complete(CKDEPI, LOGPRO, fill = list(dose.c = NA)) %>% 
  ggplot(aes(x = CKDEPI, y = 10^LOGPRO, fill = dose.c)) +
  geom_tile() +
  scale_fill_gradient(low = 'pink', high = 'blue') +
  scale_y_continuous(trans = 'log10')

d.plot1 %>% ungroup() %>%  group_by(CKDEPI, LOGPRO) %>% 
  filter(p>=PTA) %>% 
  slice(which.min(dose.c)) %>%
  ungroup() %>% 
  complete(CKDEPI, LOGPRO, fill = list(dose.c = NA)) %>% 
  ggplot(aes(x = CKDEPI, y = dose.c,)) +
  geom_point(size=.5) + geom_line() +
  facet_wrap(~LOGPRO)

d.plot1 %>% ungroup() %>%  group_by(CKDEPI, LOGPRO) %>% 
  filter(p>=PTA) %>% 
  slice(which.min(dose.c)) %>% 
  ungroup() %>% 
  complete(CKDEPI, LOGPRO, fill = list(dose.c = NA)) %>% 
  ggplot(aes(x = 10^LOGPRO, y = dose.c,)) +
  geom_point(size=.5) + geom_line() +
  facet_wrap(~CKDEPI) +
  scale_x_continuous(trans = 'log10')
```

### Upsampling

```{r}
d.plot1.up <- d.plot1 %>% ungroup() %>%  group_by(CKDEPI, LOGPRO) %>% 
  filter(p>=PTA) %>% 
  slice(which.min(dose.c)) %>% 
  ungroup() %>% 
  complete(CKDEPI, LOGPRO, fill = list(dose.c = NA)) %>% 
  ungroup() %>% nest() %>% 
  mutate(tps = map(data, ~fields::Tps(.[c('CKDEPI','LOGPRO')], .$dose.c))
         , tps.xy = map(tps, ~expand_grid(CKDEPI.c = CKDEPI.c.range, LOGPRO.c = LOGPRO.c.range))
         , dose.c = map(tps, ~predict(., expand_grid(CKDEPI.c.range, LOGPRO.c.range), lambda = 0)[,1])) %>% 
  unnest(c(tps.xy, dose.c)) 
```

```{r}
d.plot1.up %>% ungroup() %>%  group_by(CKDEPI.c, LOGPRO.c) %>% 
  filter(CKDEPI.c < 21) %>% 
  ggplot(aes(x = LOGPRO.c, y = dose.c,)) +
  geom_point(size=.1) + geom_line() +
  geom_point(data = dd %>% ungroup() %>%  group_by(CKDEPI, LOGPRO) %>% filter(p>=PTA) %>% slice(which.min(dose)) %>% rename(CKDEPI.c = CKDEPI, LOGPRO.c = LOGPRO) %>% filter(CKDEPI.c < 21), aes(x=LOGPRO.c, y = dose), size=2) +
  facet_wrap(~CKDEPI.c)
```


```{r}
d.plot1.up %>% 
  ggplot(aes(x = CKDEPI.c, y = 10^LOGPRO.c, fill = dose.c)) +
  geom_tile() +
  scale_fill_gradient(low = 'pink', high = 'blue') +
  scale_y_continuous(trans = 'log10')

d.plot1.up %>% 
  ggplot(aes(x = CKDEPI.c, y = 10^LOGPRO.c, z = dose.c)) +
  geom_contour(breaks = seq(1,18)) +
  metR::geom_text_contour(stroke = 0.2, breaks = seq(1,18), skip = 0) +
  geom_contour(size=.1, breaks = seq(1.1,1.9,.1), color = 'grey') +
  metR::geom_text_contour(stroke = 0.1, size = 2, breaks = seq(1.1,1.9, .1), skip = 0, color = 'black', label.placement = label_placement_fraction(frac = c(.1,.9))) +
  theme_bw() +
  scale_y_continuous(trans = 'log10')
```

## Only CKD x LOGPRO

```{r interpolation2}
d.plot2 <- dd %>%ungroup() %>% group_by(dose) %>% nest() %>% 
  mutate(tps = map(data, ~fields::Tps(.[c('CKDEPI','LOGPRO')], .$p))
         , tps.xy = map(tps, ~expand_grid(CKDEPI.c = CKDEPI.c.range, LOGPRO.c = LOGPRO.c.range))
         , p = map(tps, ~predict(., expand_grid(CKDEPI.c.range, LOGPRO.c.range), lambda = 0.1)[,1])) %>% 
  unnest(c(tps.xy, p))

d.plot2 %>% 
  ggplot(aes(x = CKDEPI.c, y = LOGPRO.c, fill = p)) +
  geom_tile() +
  facet_wrap(~dose) +
  scale_fill_gradient2(low = 'red', mid = 'yellow', high = 'darkgreen', midpoint = .5)

d.plot2 %>% 
  filter(CKDEPI.c %in% CKDEPI.c.subset & LOGPRO.c %in% LOGPRO.c.subset) %>% 
  ggplot(aes(x = dose, y = p)) +
  geom_point() + geom_line() + 
  facet_grid(CKDEPI.c ~ LOGPRO.c) +
  scale_fill_gradient2(low = 'red', mid = 'yellow', high = 'darkgreen', midpoint = .5)
```

### Inversion

```{r inversion2}
d.plot2 %>% ungroup() %>%  group_by(CKDEPI.c, LOGPRO.c) %>% 
  filter(p>=PTA) %>% slice(which.min(dose)) %>% 
  ggplot(aes(x = CKDEPI.c, y = LOGPRO.c, fill = as.factor(dose))) +
  geom_tile() 
```

## Both

NOT RUN

```{r interpolation3, eval=FALSE}
d.plot3 <- dd %>% ungroup() %>% nest() %>% 
  mutate(tps = map(data, ~fields::Tps(.[c('CKDEPI','LOGPRO','dose')], .$p))
         , tps.xyz = map(tps, ~expand_grid(CKDEPI.c = CKDEPI.c.range
                                           , LOGPRO.c = LOGPRO.c.range
                                           , dose.c = dose.c.range))
         , p = map(tps, ~predict(., expand_grid(CKDEPI.c.range, LOGPRO.c.range, dose.c.range), lambda = 0.1)[,1])) %>% 
  unnest(c(tps.xyz, p))

d.plot3 %>% 
  filter(dose.c %in% dose.c.subset) %>% 
  ggplot(aes(x = CKDEPI.c, y = LOGPRO.c, fill = p)) +
  geom_tile() +
  facet_wrap(~dose.c) +
  scale_fill_gradient2(low = 'red', mid = 'yellow', high = 'darkgreen', midpoint = .5)

d.plot3 %>% 
  filter(CKDEPI.c %in% CKDEPI.c.subset & LOGPRO.c %in% LOGPRO.c.subset) %>% 
  ggplot(aes(x = dose.c, y = p)) +
  geom_line() + 
  facet_grid(CKDEPI.c ~ LOGPRO.c) +
  scale_fill_gradient2(low = 'red', mid = 'yellow', high = 'darkgreen', midpoint = .5)
```

### Inversion

```{r inversion3, eval=FALSE}
d.plot3 %>% ungroup() %>%  group_by(CKDEPI.c, LOGPRO.c) %>% 
  filter(p>=PTA) %>% slice(which.min(dose.c)) %>% 
  ggplot(aes(x = CKDEPI.c, y = LOGPRO.c, fill = dose.c)) +
  geom_tile() +
  scale_fill_gradient(low = 'pink', high = 'blue')

d.plot3 %>% ungroup() %>%  group_by(CKDEPI.c, LOGPRO.c) %>% 
  filter(p>=PTA) %>% slice(which.min(dose.c)) %>% 
  ggplot(aes(x = CKDEPI.c, y = LOGPRO.c, z = dose.c)) +
  geom_contour()
```

